name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.swift'
      - '.github/workflows/CI.yml'
  pull_request:
    paths:
      - '**/*.swift'
      - '.github/workflows/CI.yml'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  Xcode:
    strategy:
      matrix:
        xcode_version: ['16.0', '16.1', '16.2']
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v4
      - run: swift -version
      - run: swift test -c release -Xswiftc -enable-testing

  Coverage:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: swift test -c release -Xswiftc -enable-testing --enable-code-coverage
      - run: find .build/release/codecov/ -name "*.profraw" -print0 | xargs -0 xcrun llvm-profdata merge -sparse -o .build/release/codecov/default.profdata
      - run: xcrun llvm-cov export -summary-only -ignore-filename-regex 'PackagerTests|resource_bundle_accessor.swift|.*Deprecated.*$' .build/release/PackagerTests.xctest/Contents/MacOS/PackagerTests -instr-profile .build/release/codecov/default.profdata > .build/coverage.json
      - run: (cat .build/coverage.json|jq '.data[0]["totals"]["lines"]["percent"]' | grep -Eq  "100") && { exit 0; } || { echo 'Please make sure that the test suite covers all framework code paths.'; exit 1; }